export const CustomExceptions = {
  //USER
  USER_NOT_FOUND: {
    statusCode: 2000,
    message: "존재하지 않는 유저입니다.",
    result: { fcmTokens: "" },
  },
  EMAIL_ALREADY_EXISTS: {
    statusCode: 2001,
    message: "이미 존재하는 이메일입니다.",
    result: { userIdx: "" },
  },
  NICKNAME_ALREADY_EXISTS: {
    statusCode: 2002,
    message: "이미 존재하는 닉네임입니다.",
    result: { userIdx: "" },
  },
  PHONE_ALREADY_EXISTS: {
    statusCode: 2003,
    message: "이미 존재하는 핸드폰 번호입니다.",
    result: { userIdx: "" },
  },
  FCMTOKEN_NOT_FOUND: {
    statusCode: 2004,
    message: "fcmToken이 존재하지 않습니다.",
    result: { fcmTokens: {} },
  },
  // POST
  EXCEED_CONTENT_LENGTH: {
    statusCode: 2005,
    message: `content가 제한 글자수 1자를 초과했습니다.`,
    result: {
      userIdx: null,
      category: "",
      title: "",
      content: "",
      likeNum: null,
      viewNum: null,
      postIdx: null,
      createAt: "",
      updatedAt: "",
      nickName: "",
      imagePath: [],
      commentList: [],
    },
  },
  USER_POSTS_NOT_FOUND: {
    statusCode: 2006,
    message: "해당 유저의 게시물이 존재하지 않습니다.",
    result: [
      {
        userIdx: null,
        category: "",
        title: "",
        content: "",
        likeNum: null,
        viewNum: null,
        postIdx: null,
        createAt: "",
        updatedAt: "",
        nickName: "",
        imagePath: [],
        commentList: [],
      },
    ],
  },
  CATEGORY_POSTS_NOT_FOUND: {
    statusCode: 2007,
    message: "해당 카테고리의 게시물이 존재하지 않습니다.",
    result: [
      {
        userIdx: null,
        category: "",
        title: "",
        content: "",
        likeNum: null,
        viewNum: null,
        postIdx: null,
        createAt: "",
        updatedAt: "",
        nickName: "",
        imagePath: [],
        commentList: [],
      },
    ],
  },
  MAX_POSTS_EXCEEDED: {
    statusCode: 2008,
    message: "전체 게시물 수를 초과하여 조회할 수 없습니다.",
    result: [
      {
        userIdx: null,
        category: "",
        title: "",
        content: "",
        likeNum: null,
        viewNum: null,
        postIdx: null,
        createAt: "",
        updatedAt: "",
        nickName: "",
        imagePath: [],
        commentList: [],
      },
    ],
  },
  POST_NOT_FOUND: {
    statusCode: 2009,
    message: "postIdx에 해당하는 게시물이 없습니다.",
    result: {
      userIdx: null,
      category: "",
      title: "",
      content: "",
      likeNum: null,
      viewNum: null,
      postIdx: null,
      createAt: "",
      updatedAt: "",
      nickName: "",
      imagePath: [],
      commentList: [],
    },
  },
  LIKE_NOT_FOUND: {
    statusCode: 2010,
    message: "해당 게시물에 좋아요를 누르지 않은 유저입니다.",
    result: {
      userIdx: null,
      category: "",
      title: "",
      content: "",
      likeNum: null,
      viewNum: null,
      postIdx: null,
      createAt: "",
      updatedAt: "",
      nickName: "",
      imagePath: [],
      commentList: [],
    },
  },
  //COMMENT
  NOT_FOUNT_POST: {
    statusCode: 2011,
    message: "존재하지 않는 게시물입니다.",
    result: {
      commentIdx: null,
      postIdx: null,
      userIdx: null,
      parentCommentIdx: null,
      depth: null,
      commentAt: "",
      commentContent: "",
      isDeleted: null,
    },
  },
  NOT_FOUND_COMMENT: {
    statusCode: 2012,
    message: "해당 게시물의 댓글이 존재하지 않습니다.",
    result: [
      {
        commentIdx: null,
        postIdx: null,
        userIdx: null,
        parentCommentIdx: null,
        depth: null,
        commentAt: "",
        commentContent: "",
        isDeleted: null,
      },
    ],
  },
};
